PREAMBLE 
/////////////////////////////////////////////////////////////////////////  
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING	    
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//																			
//  DO NOT EDIT THIS FILE!													
//  Loading an edited TLA file in the TLA 700 application can				
//  cause the application to crash.  Editing this file can not				
//  only introduce errors in the text portion of the file but				
//  most editors (e.g. Notepad) will silently corrupt the binary			
//  data portion of the file, causing the TLA 700 application to			
//  crash when the corrupted file is loaded by the application.				
//																			
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//																			
/////////////////////////////////////////////////////////////////////////
CafcCompositeCell "Preamble" "$$" {
	CafcStringCell "UserComment" "$$" = { "PCI Support Package Instrument Setup"  }
	CafcByteCell "FileType" "$$" = { 1  0 255 }
	CafcArrayCell "InstrumentAfcNames" "$$" {
		CafcStringCell "NoName" "$$" = { "PCI"  }
	}
	CafcArrayCell "InstrumentUserNames" "$$" {
		CafcStringCell "NoName" "$$" = { "PCI"  }
	}
	CafcArrayCell "InstrumentSamples" "$$" {
		CafcLongCell "NoName" "$$" = { -1  }
	}
	CafcArrayCell "InstrumentTypes" "$$" {
		CafcByteCell "NoName" "$$" = { 20  0 255 }
	}
	CafcArrayCell "ViewAfcNames" "$$" {
	}
	CafcArrayCell "ViewUserNames" "$$" {
	}
	CafcArrayCell "ViewTypes" "$$" {
	}
	CafcStringCell "ProductVersionNoString" "$$" = { "1.0.261.0"  }
}
CapRoot "Root" "$$" {
	CjmInstrument "PCI" "$PCI$" {
		CafcLongLongCell "SysTrigTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
		CafcStringCell "UserName" "$$" = { "PCI"  }
		CafcLongLongCell "TimeSkew" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
		CcmSaveDataCompositeCell "TbTimebaseSet" "$$" {
			CjmTimebaseData "TbMainTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 0  }
				CafcLongCell "DaBytesPerSample" "$$" = { 26  }
				CafcByteCell "DaFinalState" "$$" = { 1  0 255 }
				CafcBooleanCell "DaTrigPresent" "$$" = { FALSE  }
				CafcLongCell "DaTrigSample" "$$" = { 0  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "DaTrigType" "$$" = { 0  0 255 }
				CafcBooleanCell "DaTrigAll" "$$" = { FALSE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongCell "DaStartDate" "$$" = { 0  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { TRUE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CcmDataSet "DaSetViolation" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CafcByteCell "jmCtmr1Mode" "$$" = { 0  0 255 }
				CafcLongLongCell "jmCtmr1Value" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "jmCtmr2Mode" "$$" = { 0  0 255 }
				CafcLongLongCell "jmCtmr2Value" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "jmCurSyncSpeed" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "jmStatusBitType" "$$" = { 0  0 255 }
				CafcByteCell "jmClkMode" "$$" = { 0  0 255 }
				CafcLongCell "jmTimestampReplicant" "$$" = { 0  }
				CafcBooleanCell "jmDemuxClkQual" "$$" = { TRUE  }
				CjmCompareData "CmpData" "$$" {
					CafcBooleanCell "CmpEnable" "$$" = { FALSE  }
					CafcBooleanCell "CmpRuntimeEnable" "$$" = { FALSE  }
					CafcByteCell "CmpRuntimeCond" "$$" = { 0  0 255 }
					
					CafcBooleanCell "CmpAllData" "$$" = { TRUE  }
					CafcByteCell "CmpStartRef" "$$" = { 2  0 255 }
					CafcLongCell "CmpStartSample" "$$" = { 0  }
					CafcLongCell "CmpCount" "$$" = { 0  }
					CafcByteCell "CmpAlignRef" "$$" = { 1  0 255 }
					CafcLongCell "CmpAlignOffset" "$$" = { 0  }
				}
				CafcArrayCell "CmpSuppression" "$$" {
				}
				CafcByteCell "CmpSupOpMode" "$$" = { 0  0 255 }
				CafcLongLongCell "CmpSupOpCount" "$$" = { 1024 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcBooleanCell "CmpSupTrigRelative" "$$" = { TRUE  }
				CafcBooleanCell "smSaveSystemType" "$$" = { FALSE  }
				CafcLongCell "JmXFactor" "$$" = { 1  }
			}
			CjmTimebaseData "TbHiResTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 0  }
				CafcLongCell "DaBytesPerSample" "$$" = { 17  }
				CafcByteCell "DaFinalState" "$$" = { 1  0 255 }
				CafcBooleanCell "DaTrigPresent" "$$" = { FALSE  }
				CafcLongCell "DaTrigSample" "$$" = { 0  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "DaTrigType" "$$" = { 0  0 255 }
				CafcBooleanCell "DaTrigAll" "$$" = { FALSE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongCell "DaStartDate" "$$" = { 0  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { TRUE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CafcLongCell "JmXFactor" "$$" = { 1  }
			}
		}
		CjmConfig "CommonConfigModel" "$$" {
			CafcLongCell "CoNumModules" "$$" = { 1  }
			CafcLongCell "CoNumChannels" "$$" = { 136  }
			CafcLongLongCell "CoMaxSyncRate" "$$" = { 450000000 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongLongCell "CoMaxSampleRate" "$$" = { 2000 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "CoMaxDepth" "$$" = { 67108864  }
			CafcBooleanCell "CoEnabled" "$$" = { TRUE  }
			CafcLongLongCell "CoStzOffset" "$$" = { 0 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "jmConfigMasterWidth" "$$" = { 136  }
			CafcLongCell "jmConfigSlaveWidth" "$$" = { 0  }
			CafcLongCell "jmConfigSlave2Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave3Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave4Width" "$$" = { 0  }
			CafcByteCell "jmSeries" "$$" = { 2  0 255 }
			CafcLongLongCell "jmMagnivuPeriod" "$$" = { 125 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "jmMagnivuDepth" "$$" = { 16384  }
			CafcLongCell "jmWordRecDataSize" "$$" = { 17  }
			CafcLongCell "jmWordRecStatusSize" "$$" = { 1  }
			CafcArrayCell "jmDisplayStatusBitList" "$$" {
				CafcByteCell "NoName" "$$" = { 3  0 255 }
				CafcByteCell "NoName" "$$" = { 4  0 255 }
				CafcByteCell "NoName" "$$" = { 5  0 255 }
			}
			CafcArrayCell "jmTriggerStatusBitList" "$$" {
				CafcByteCell "NoName" "$$" = { 3  0 255 }
			}
		}
		CjmScreenParam "jmScreenParams" "$$" {
			CcmToolbarParamSet "cmToolbarParamSet" "$$" {
				CafcBooleanCell "cmToolbarParamSetUseDefault" "$$" = { FALSE  }
				CcmToolbarParams "jsFileBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { -2  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jsSetupBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 99  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
			}
			CafcLongCell "FrameWidth" "$$" = { 546  }
			CafcLongCell "FrameHeight" "$$" = { 481  }
			CafcLongCell "FrameXPos" "$$" = { 303  }
			CafcLongCell "FrameYPos" "$$" = { 134  }
			CafcByteCell "ShowState" "$$" = { 3  0 255 }
			CafcByteCell "jmSParamSetupChannelsVisible" "$$" = { 1  0 1 }
			CafcByteCell "jmSParamSetupShowGroups" "$$" = { 0  0 2 }
		}
		CjmChannelInfo "CiChannelInfo" "$$" {
			CjmChannelArray "CiChannels" "$$" {
				CjmChannel "A0_0" "$PCI_CLK$" {
				}
				CjmChannel "A0_1" "$PCI_RST$" {
				}
				CjmChannel "A0_2" "$PCI_FRAME$" {
				}
				CjmChannel "A0_3" "$PCI_IRDY$" {
				}
				CjmChannel "A0_4" "$PCI_TRDY$" {
				}
				CjmChannel "A0_5" "$PCI_STOP$" {
				}
				CjmChannel "A0_6" "$PCI_DEVSEL$" {
				}
				CjmChannel "A0_7" "$PCI_PAR$" {
				}
				CjmChannel "A0_8" "$PCI_PERR$" {
				}
				CjmChannel "A0_9" "$PCI_SERR$" {
				}
				CjmChannel "A0_10" "$PCI_INTA$" {
				}
				CjmChannel "A0_11" "$PCI_INTB$" {
				}
				CjmChannel "A0_12" "$PCI_INTC$" {
				}
				CjmChannel "A0_13" "$PCI_INTD$" {
				}
				CjmChannel "A0_14" "$PCI_GNT$" {
				}
				CjmChannel "A0_15" "$PCI_REQ$" {
				}
				CjmChannel "A0_16" "$PCI_RESERVED$" {
				}
				CjmChannel "A0_17" "$PCI_C_BE0$" {
				}
				CjmChannel "A0_18" "$PCI_C_BE1$" {
				}
				CjmChannel "A0_19" "$PCI_C_BE2$" {
				}
				CjmChannel "A0_20" "$PCI_C_BE3$" {
				}
				CjmChannel "A0_21" "$PCI_IDSEL$" {
				}
				CjmChannel "A0_22" "$PCI_LOCK$" {
				}
				CjmChannel "A0_23" "$PCI_AD0$" {
				}
				CjmChannel "A0_24" "$PCI_AD1$" {
				}
				CjmChannel "A0_25" "$PCI_AD2$" {
				}
				CjmChannel "A0_26" "$PCI_AD3$" {
				}
				CjmChannel "A0_27" "$PCI_AD4$" {
				}
				CjmChannel "A0_28" "$PCI_AD5$" {
				}
				CjmChannel "A0_29" "$PCI_AD6$" {
				}
				CjmChannel "A0_30" "$PCI_AD7$" {
				}
				CjmChannel "A0_31" "$PCI_AD8$" {
				}
				CjmChannel "A1_0" "$PCI_AD9$" {
				}
				CjmChannel "A1_1" "$PCI_AD10$" {
				}
				CjmChannel "A1_2" "$PCI_AD11$" {
				}
				CjmChannel "A1_3" "$PCI_AD12$" {
				}
				CjmChannel "A1_4" "$PCI_AD13$" {
				}
				CjmChannel "A1_5" "$PCI_AD14$" {
				}
				CjmChannel "A1_6" "$PCI_AD15$" {
				}
				CjmChannel "A1_7" "$PCI_AD16$" {
				}
				CjmChannel "A1_8" "$PCI_AD17$" {
				}
				CjmChannel "A1_9" "$PCI_AD18$" {
				}
				CjmChannel "A1_10" "$PCI_AD19$" {
				}
				CjmChannel "A1_11" "$PCI_AD20$" {
				}
				CjmChannel "A1_12" "$PCI_AD21$" {
				}
				CjmChannel "A1_13" "$PCI_AD22$" {
				}
				CjmChannel "A1_14" "$PCI_AD23$" {
				}
				CjmChannel "A1_15" "$PCI_AD24$" {
				}
				CjmChannel "A1_16" "$PCI_AD25$" {
				}
				CjmChannel "A1_17" "$PCI_AD26$" {
				}
				CjmChannel "A1_18" "$PCI_AD27$" {
				}
				CjmChannel "A1_19" "$PCI_AD28$" {
				}
				CjmChannel "A1_20" "$PCI_AD29$" {
				}
				CjmChannel "A1_21" "$PCI_AD30$" {
				}
				CjmChannel "A1_22" "$PCI_AD31$" {
				}
			}
			CjmUserGroups "jmUserGroups" "$$" {
				CjmChannelGroup "UserGrp" "$PCI$" {
					CafcStringCell "UserName" "$$" = { "PCI"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "PCI_CLK,PCI_RST,PCI_FRAME,PCI_IRDY,PCI_TRDY,PCI_STOP,PCI_DEVSEL,PCI_PAR,PCI_PERR,PCI_SERR,PCI_INTA,PCI_INTB,PCI_INTC,PCI_INTD,PCI_GNT,PCI_REQ,PCI_RESERVED,PCI_C_BE0,PCI_C_BE1,PCI_C_BE2,PCI_C_BE3,PCI_IDSEL,PCI_LOCK,PCI_AD0,PCI_AD1,PCI_AD2,PCI_AD3,PCI_AD4,PCI_AD5,PCI_AD6,PCI_AD7,PCI_AD8,PCI_AD9,PCI_AD10,PCI_AD11,PCI_AD12,PCI_AD13,PCI_AD14,PCI_AD15,PCI_AD16,PCI_AD17,PCI_AD18,PCI_AD19,PCI_AD20,PCI_AD21,PCI_AD22,PCI_AD23,PCI_AD24,PCI_AD25,PCI_AD26,PCI_AD27,PCI_AD28,PCI_AD29,PCI_AD30,PCI_AD31"  }
				}
				CjmChannelGroup "UserGrp" "$PCISig$" {
					CafcStringCell "UserName" "$$" = { "PCISig"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "PCI_CLK,PCI_RST,PCI_FRAME,PCI_IRDY,PCI_TRDY,PCI_STOP,PCI_DEVSEL,PCI_PAR,PCI_PERR,PCI_SERR,PCI_INTA,PCI_INTB,PCI_INTC,PCI_INTD,PCI_GNT,PCI_REQ,PCI_RESERVED,PCI_C_BE0,PCI_C_BE1,PCI_C_BE2,PCI_C_BE3,PCI_IDSEL,PCI_LOCK"  }
				}
				CjmChannelGroup "UserGrp" "$PCIInt$" {
					CafcStringCell "UserName" "$$" = { "PCIInt"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "PCI_INTA,PCI_INTB,PCI_INTC,PCI_INTD"  }
				}
				CjmChannelGroup "UserGrp" "$PCIAD$" {
					CafcStringCell "UserName" "$$" = { "PCIAD"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "PCI_AD0,PCI_AD1,PCI_AD2,PCI_AD3,PCI_AD4,PCI_AD5,PCI_AD6,PCI_AD7,PCI_AD8,PCI_AD9,PCI_AD10,PCI_AD11,PCI_AD12,PCI_AD13,PCI_AD14,PCI_AD15,PCI_AD16,PCI_AD17,PCI_AD18,PCI_AD19,PCI_AD20,PCI_AD21,PCI_AD22,PCI_AD23,PCI_AD24,PCI_AD25,PCI_AD26,PCI_AD27,PCI_AD28,PCI_AD29,PCI_AD30,PCI_AD31"  }
				}
			}
		}
		CcmSupportedLA "SupportedLA" "$$" {
			CafcStringCell "PackageName" "$$" = { "PCI"  }
			RDAInternalOpMarkSet "RDAOpMarkSet" "$$" {
			}
		}
	}
}