PREAMBLE 
/////////////////////////////////////////////////////////////////////////  
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING	    
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//																			
//  DO NOT EDIT THIS FILE!													
//  Loading an edited TLA file in the TLA 700 application can				
//  cause the application to crash.  Editing this file can not				
//  only introduce errors in the text portion of the file but				
//  most editors (e.g. Notepad) will silently corrupt the binary			
//  data portion of the file, causing the TLA 700 application to			
//  crash when the corrupted file is loaded by the application.				
//																			
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING		
//																			
/////////////////////////////////////////////////////////////////////////
CafcCompositeCell "Preamble" "$$" {
	CafcStringCell "UserComment" "$$" = { "ISA 8/16-bit Support Package Instrument Setup"  }
	CafcByteCell "FileType" "$$" = { 1  0 255 }
	CafcArrayCell "InstrumentAfcNames" "$$" {
		CafcStringCell "NoName" "$$" = { "ISA"  }
	}
	CafcArrayCell "InstrumentUserNames" "$$" {
		CafcStringCell "NoName" "$$" = { "ISA"  }
	}
	CafcArrayCell "InstrumentSamples" "$$" {
		CafcLongCell "NoName" "$$" = { -1  }
	}
	CafcArrayCell "InstrumentTypes" "$$" {
		CafcByteCell "NoName" "$$" = { 20  0 255 }
	}
	CafcArrayCell "ViewAfcNames" "$$" {
	}
	CafcArrayCell "ViewUserNames" "$$" {
	}
	CafcArrayCell "ViewTypes" "$$" {
	}
	CafcStringCell "ProductVersionNoString" "$$" = { "1.0.261.0"  }
}
CapRoot "Root" "$$" {
	CjmInstrument "ISA" "$ISA$" {
		CafcLongLongCell "SysTrigTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
		CafcStringCell "UserName" "$$" = { "ISA"  }
		CafcLongLongCell "TimeSkew" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
		CcmSaveDataCompositeCell "TbTimebaseSet" "$$" {
			CjmTimebaseData "TbMainTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 0  }
				CafcLongCell "DaBytesPerSample" "$$" = { 26  }
				CafcByteCell "DaFinalState" "$$" = { 1  0 255 }
				CafcBooleanCell "DaTrigPresent" "$$" = { FALSE  }
				CafcLongCell "DaTrigSample" "$$" = { 0  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "DaTrigType" "$$" = { 0  0 255 }
				CafcBooleanCell "DaTrigAll" "$$" = { FALSE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongCell "DaStartDate" "$$" = { 0  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { TRUE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CcmDataSet "DaSetViolation" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CafcByteCell "jmCtmr1Mode" "$$" = { 0  0 255 }
				CafcLongLongCell "jmCtmr1Value" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "jmCtmr2Mode" "$$" = { 0  0 255 }
				CafcLongLongCell "jmCtmr2Value" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "jmCurSyncSpeed" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "jmStatusBitType" "$$" = { 0  0 255 }
				CafcByteCell "jmClkMode" "$$" = { 0  0 255 }
				CafcLongCell "jmTimestampReplicant" "$$" = { 0  }
				CafcBooleanCell "jmDemuxClkQual" "$$" = { TRUE  }
			}
			CjmTimebaseData "TbHiResTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 0  }
				CafcLongCell "DaBytesPerSample" "$$" = { 17  }
				CafcByteCell "DaFinalState" "$$" = { 1  0 255 }
				CafcBooleanCell "DaTrigPresent" "$$" = { FALSE  }
				CafcLongCell "DaTrigSample" "$$" = { 0  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcByteCell "DaTrigType" "$$" = { 0  0 255 }
				CafcBooleanCell "DaTrigAll" "$$" = { FALSE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 0 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongCell "DaStartDate" "$$" = { 0  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 1 1 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { TRUE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CafcLongCell "JmXFactor" "$$" = { 1  }
			}
		}
		CjmConfig "CommonConfigModel" "$$" {
			CafcLongCell "CoNumModules" "$$" = { 1  }
			CafcLongCell "CoNumChannels" "$$" = { 136  }
			CafcLongLongCell "CoMaxSyncRate" "$$" = { 450000000 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongLongCell "CoMaxSampleRate" "$$" = { 2000 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "CoMaxDepth" "$$" = { 67108864  }
			CafcBooleanCell "CoEnabled" "$$" = { TRUE  }
			CafcLongLongCell "CoStzOffset" "$$" = { 0 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "jmConfigMasterWidth" "$$" = { 136  }
			CafcLongCell "jmConfigSlaveWidth" "$$" = { 0  }
			CafcLongCell "jmConfigSlave2Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave3Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave4Width" "$$" = { 0  }
			CafcByteCell "jmSeries" "$$" = { 2  0 255 }
			CafcLongLongCell "jmMagnivuPeriod" "$$" = { 125 0 9223372036854775807 1 AFC_FIXED_INCR  }
			CafcLongCell "jmMagnivuDepth" "$$" = { 16384  }
			CafcLongCell "jmWordRecDataSize" "$$" = { 17  }
			CafcLongCell "jmWordRecStatusSize" "$$" = { 1  }
		}
		CjmChannelInfo "CiChannelInfo" "$$" {
			CjmChannelArray "CiChannels" "$$" {
				// ISA Control Signals Group (Group 0)
				CjmChannel "A0_0" "$ISA_BCLK$" {
				}
				CjmChannel "A0_1" "$ISA_ALE$" {
				}
				CjmChannel "A0_2" "$ISA_IOR$" {
				}
				CjmChannel "A0_3" "$ISA_IOW$" {
				}
				CjmChannel "A0_4" "$ISA_MEMR$" {
				}
				CjmChannel "A0_5" "$ISA_MEMW$" {
				}
				CjmChannel "A0_6" "$ISA_REFRESH$" {
				}
				CjmChannel "A0_7" "$ISA_MASTER$" {
				}
				CjmChannel "A1_0" "$ISA_SBHE$" {
				}
				CjmChannel "A1_1" "$ISA_IOCHRDY$" {
				}
				CjmChannel "A1_2" "$ISA_AEN$" {
				}
				CjmChannel "A1_3" "$ISA_IOCHK$" {
				}
				CjmChannel "A1_4" "$ISA_RESET$" {
				}
				CjmChannel "A1_5" "$ISA_OSC$" {
				}
				
				// ISA Address Lines (Group 1) - Ports A2 through A5
				CjmChannel "A2_0" "$ISA_ADDR_00$" {
				}
				CjmChannel "A2_1" "$ISA_ADDR_01$" {
				}
				CjmChannel "A2_2" "$ISA_ADDR_02$" {
				}
				CjmChannel "A2_3" "$ISA_ADDR_03$" {
				}
				CjmChannel "A2_4" "$ISA_ADDR_04$" {
				}
				CjmChannel "A2_5" "$ISA_ADDR_05$" {
				}
				CjmChannel "A2_6" "$ISA_ADDR_06$" {
				}
				CjmChannel "A2_7" "$ISA_ADDR_07$" {
				}
				CjmChannel "A3_0" "$ISA_ADDR_08$" {
				}
				CjmChannel "A3_1" "$ISA_ADDR_09$" {
				}
				CjmChannel "A3_2" "$ISA_ADDR_10$" {
				}
				CjmChannel "A3_3" "$ISA_ADDR_11$" {
				}
				CjmChannel "A3_4" "$ISA_ADDR_12$" {
				}
				CjmChannel "A3_5" "$ISA_ADDR_13$" {
				}
				CjmChannel "A3_6" "$ISA_ADDR_14$" {
				}
				CjmChannel "A3_7" "$ISA_ADDR_15$" {
				}
				CjmChannel "A4_0" "$ISA_ADDR_16$" {
				}
				CjmChannel "A4_1" "$ISA_ADDR_17$" {
				}
				CjmChannel "A4_2" "$ISA_ADDR_18$" {
				}
				CjmChannel "A4_3" "$ISA_ADDR_19$" {
				}
				CjmChannel "A4_4" "$ISA_ADDR_20$" {
				}
				CjmChannel "A4_5" "$ISA_ADDR_21$" {
				}
				CjmChannel "A4_6" "$ISA_ADDR_22$" {
				}
				CjmChannel "A4_7" "$ISA_ADDR_23$" {
				}
				
				// ISA Data Lines (Group 2) - Port A5
				CjmChannel "A5_0" "$ISA_DATA_00$" {
				}
				CjmChannel "A5_1" "$ISA_DATA_01$" {
				}
				CjmChannel "A5_2" "$ISA_DATA_02$" {
				}
				CjmChannel "A5_3" "$ISA_DATA_03$" {
				}
				CjmChannel "A5_4" "$ISA_DATA_04$" {
				}
				CjmChannel "A5_5" "$ISA_DATA_05$" {
				}
				CjmChannel "A5_6" "$ISA_DATA_06$" {
				}
				CjmChannel "A5_7" "$ISA_DATA_07$" {
				}
				CjmChannel "A6_0" "$ISA_DATA_08$" {
				}
				CjmChannel "A6_1" "$ISA_DATA_09$" {
				}
				CjmChannel "A6_2" "$ISA_DATA_10$" {
				}
				CjmChannel "A6_3" "$ISA_DATA_11$" {
				}
				CjmChannel "A6_4" "$ISA_DATA_12$" {
				}
				CjmChannel "A6_5" "$ISA_DATA_13$" {
				}
				CjmChannel "A6_6" "$ISA_DATA_14$" {
				}
				CjmChannel "A6_7" "$ISA_DATA_15$" {
				}
				
				// ISA DMA Signals (Group 3) - Ports A7, A8
				CjmChannel "A7_0" "$ISA_DACK0$" {
				}
				CjmChannel "A7_1" "$ISA_DACK1$" {
				}
				CjmChannel "A7_2" "$ISA_DACK2$" {
				}
				CjmChannel "A7_3" "$ISA_DACK3$" {
				}
				CjmChannel "A7_4" "$ISA_DACK5$" {
				}
				CjmChannel "A7_5" "$ISA_DACK6$" {
				}
				CjmChannel "A7_6" "$ISA_DACK7$" {
				}
				CjmChannel "A7_7" "$ISA_DRQ0$" {
				}
				CjmChannel "A8_0" "$ISA_DRQ1$" {
				}
				CjmChannel "A8_1" "$ISA_DRQ2$" {
				}
				CjmChannel "A8_2" "$ISA_DRQ3$" {
				}
				CjmChannel "A8_3" "$ISA_DRQ5$" {
				}
				CjmChannel "A8_4" "$ISA_DRQ6$" {
				}
				CjmChannel "A8_5" "$ISA_DRQ7$" {
				}
				CjmChannel "A8_6" "$ISA_TC$" {
				}
				
				// ISA IRQ Signals (Group 4) - Port A9
				CjmChannel "A9_0" "$ISA_IRQ2$" {
				}
				CjmChannel "A9_1" "$ISA_IRQ3$" {
				}
				CjmChannel "A9_2" "$ISA_IRQ4$" {
				}
				CjmChannel "A9_3" "$ISA_IRQ5$" {
				}
				CjmChannel "A9_4" "$ISA_IRQ6$" {
				}
				CjmChannel "A9_5" "$ISA_IRQ7$" {
				}
				CjmChannel "A9_6" "$ISA_IRQ10$" {
				}
				CjmChannel "A9_7" "$ISA_IRQ11$" {
				}
				CjmChannel "A10_0" "$ISA_IRQ12$" {
				}
				CjmChannel "A10_1" "$ISA_IRQ14$" {
				}
				CjmChannel "A10_2" "$ISA_IRQ15$" {
				}
				CjmChannel "A10_3" "$ISA_IRQ9$" {
				}
			}
			CjmProbeSet "jmProbeSet" "$$" {
				CjmProbe "A3A2" "$$" {
					CafcLongLongCell "jmProbeDataThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
					CafcLongLongCell "jmProbeClockThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
				}
				CjmProbe "A1A0" "$$" {
					CafcLongLongCell "jmProbeDataThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
					CafcLongLongCell "jmProbeClockThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
				}
				CjmProbe "A5A4" "$$" {
					CafcLongLongCell "jmProbeDataThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
					CafcLongLongCell "jmProbeClockThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
				}
				CjmProbe "A7A6" "$$" {
					CafcLongLongCell "jmProbeDataThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
					CafcLongLongCell "jmProbeClockThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
				}
				CjmProbe "A9A8" "$$" {
					CafcLongLongCell "jmProbeDataThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
					CafcLongLongCell "jmProbeClockThreshold" "$$" = { 1500000000000 -2000000000000 4500000000000 5000000000 AFC_FIXED_INCR  }
				}
			}
			CjmUserGroups "jmUserGroups" "$$" {
				CjmChannelGroup "UserGrp" "$ISA_Control$" {
					CafcStringCell "UserName" "$$" = { "ISA_Control"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_BCLK,ISA_ALE,ISA_IOR,ISA_IOW,ISA_MEMR,ISA_MEMW,ISA_REFRESH,ISA_MASTER,ISA_SBHE,ISA_IOCHRDY,ISA_AEN,ISA_IOCHK,ISA_RESET,ISA_OSC"  }
				}
				CjmChannelGroup "UserGrp" "$ISA_Address$" {
					CafcStringCell "UserName" "$$" = { "ISA_Address"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_ADDR_00,ISA_ADDR_01,ISA_ADDR_02,ISA_ADDR_03,ISA_ADDR_04,ISA_ADDR_05,ISA_ADDR_06,ISA_ADDR_07,ISA_ADDR_08,ISA_ADDR_09,ISA_ADDR_10,ISA_ADDR_11,ISA_ADDR_12,ISA_ADDR_13,ISA_ADDR_14,ISA_ADDR_15,ISA_ADDR_16,ISA_ADDR_17,ISA_ADDR_18,ISA_ADDR_19,ISA_ADDR_20,ISA_ADDR_21,ISA_ADDR_22,ISA_ADDR_23"  }
				}
				CjmChannelGroup "UserGrp" "$ISA_Data$" {
					CafcStringCell "UserName" "$$" = { "ISA_Data"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_DATA_00,ISA_DATA_01,ISA_DATA_02,ISA_DATA_03,ISA_DATA_04,ISA_DATA_05,ISA_DATA_06,ISA_DATA_07,ISA_DATA_08,ISA_DATA_09,ISA_DATA_10,ISA_DATA_11,ISA_DATA_12,ISA_DATA_13,ISA_DATA_14,ISA_DATA_15"  }
				}
				CjmChannelGroup "UserGrp" "$ISA_DMA$" {
					CafcStringCell "UserName" "$$" = { "ISA_DMA"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_DACK0,ISA_DACK1,ISA_DACK2,ISA_DACK3,ISA_DACK5,ISA_DACK6,ISA_DACK7,ISA_DRQ0,ISA_DRQ1,ISA_DRQ2,ISA_DRQ3,ISA_DRQ5,ISA_DRQ6,ISA_DRQ7,ISA_TC"  }
				}
				CjmChannelGroup "UserGrp" "$ISA_IRQ$" {
					CafcStringCell "UserName" "$$" = { "ISA_IRQ"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_IRQ2,ISA_IRQ3,ISA_IRQ4,ISA_IRQ5,ISA_IRQ6,ISA_IRQ7,ISA_IRQ10,ISA_IRQ11,ISA_IRQ12,ISA_IRQ14,ISA_IRQ15,ISA_IRQ9"  }
				}
				CjmChannelGroup "UserGrp" "$ISA_All$" {
					CafcStringCell "UserName" "$$" = { "ISA_All"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { TRUE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  0 255 }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "ISA_BCLK,ISA_ALE,ISA_IOR,ISA_IOW,ISA_MEMR,ISA_MEMW,ISA_REFRESH,ISA_MASTER,ISA_SBHE,ISA_IOCHRDY,ISA_AEN,ISA_IOCHK,ISA_RESET,ISA_OSC,ISA_ADDR_00,ISA_ADDR_01,ISA_ADDR_02,ISA_ADDR_03,ISA_ADDR_04,ISA_ADDR_05,ISA_ADDR_06,ISA_ADDR_07,ISA_ADDR_08,ISA_ADDR_09,ISA_ADDR_10,ISA_ADDR_11,ISA_ADDR_12,ISA_ADDR_13,ISA_ADDR_14,ISA_ADDR_15,ISA_ADDR_16,ISA_ADDR_17,ISA_ADDR_18,ISA_ADDR_19,ISA_ADDR_20,ISA_ADDR_21,ISA_ADDR_22,ISA_ADDR_23,ISA_DATA_00,ISA_DATA_01,ISA_DATA_02,ISA_DATA_03,ISA_DATA_04,ISA_DATA_05,ISA_DATA_06,ISA_DATA_07,ISA_DATA_08,ISA_DATA_09,ISA_DATA_10,ISA_DATA_11,ISA_DATA_12,ISA_DATA_13,ISA_DATA_14,ISA_DATA_15,ISA_DACK0,ISA_DACK1,ISA_DACK2,ISA_DACK3,ISA_DACK5,ISA_DACK6,ISA_DACK7,ISA_DRQ0,ISA_DRQ1,ISA_DRQ2,ISA_DRQ3,ISA_DRQ5,ISA_DRQ6,ISA_DRQ7,ISA_TC,ISA_IRQ2,ISA_IRQ3,ISA_IRQ4,ISA_IRQ5,ISA_IRQ6,ISA_IRQ7,ISA_IRQ10,ISA_IRQ11,ISA_IRQ12,ISA_IRQ14,ISA_IRQ15,ISA_IRQ9"  }
				}
			}
		}
		CjmTrigger "jmTrigger" "$$" {
			CjmStorage "jmStorage" "$$" {
				CafcByteCell "jmStorageAcqMode" "$$" = { 0  0 255 }
				CafcByteCell "jmStorageMode" "$$" = { 0  0 255 }
				CafcByteCell "jmStartStop" "$$" = { 0  0 255 }
				CafcByteCell "jmTriggerDelay" "$$" = { 50  0 100 }
				CafcByteCell "jmHiResDelay" "$$" = { 50  0 58 }
				CafcLongLongCell "jmStorageUserDepth" "$$" = { 131072 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				CafcLongLongCell "jmStorageHiResDepth" "$$" = { 16320 16320 16320 1 AFC_FIXED_INCR  }
				CafcBooleanCell "jmStorageForceMainPrefill" "$$" = { FALSE  }
				CafcLongLongCell "jmStorageHiResStoreRate" "$$" = { 125 125 1000 1 AFC_FIXED_INCR  }
				CjmStorageClause "jmStorageClause" "$$" {
					CafcStringCell "jmClauseUiCondition" "$$" = { "( Anything )"  }
					CafcStringCell "jmClauseAction" "$$" = { "( StoreSample )"  }
					CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
				}
			}
			CjmTriggerMachine "jmTriggerMachine" "$$" {
				CafcLongCell "jmTriggerStateCount" "$$" = { 1  }
				CjmTriggerStateArray "jmTriggerStateArray" "$$" {
					CjmTriggerState "jmTriggerState1" "$$" {
						CafcLongCell "jmTriggerClauseCount" "$$" = { 1  }
						CjmTriggerClauseArray "jmTriggerClauseArray" "$$" {
							CjmTriggerClause "jmTriggerClause1" "$$" {
								CafcStringCell "jmClauseUiCondition" "$$" = { "( Macro \" \" )"  }
								CafcStringCell "jmClauseAction" "$$" = { "( TriggerAll )"  }
								CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
							}
						}
						CafcStringCell "jmTrigStateComment" "$$" = { "Trigger on the very first sample"  }
					}
				}
			}
			CjmTriggerGroups "jmTriggerGroups" "$$" {
			}
			CjmTriggerChannels "jmTriggerChannels" "$$" {
			}
			CafcByteCell "jmTabSplitWndPage" "$$" = { 0  0 255 }
			CafcBooleanCell "jmCommentsVisibleFlag" "$$" = { TRUE  }
			CafcBooleanCell "jmTrigToolbarVisibleFlag" "$$" = { TRUE  }
			CafcBooleanCell "jmTrigAdvToolbarVisibleFlag" "$$" = { TRUE  }
			CafcStringCell "jmTrigOwnerID" "$$" = { "PT:LA 1"  }
		}
		CjmClock "jmClk" "$$" {
			CafcByteCell "jmClkMode" "$$" = { 0  0 255 }
			CafcLongLongCell "jmClkIntRate" "$$" = { 8000000 2000 50000000000 1 AFC_FIXED_INCR  }
			CjmExternalClock "jmClkGPSyncClk" "$$" {
				CafcByteCell "jmClkGPSyncClkMode" "$$" = { 0  0 255 }
				CafcCompositeCell "jmClkGPSourceSyncClk" "$$" {
				}
				CjmExternalPresets "jmClkGPAdvPresets" "$$" {
					CafcLongCell "jmClkDefHold" "$$" = { 0  }
					CafcLongCell "jmClkDefLogin" "$$" = { 1  }
					CafcLongLongCell "jmClkDefAlignment" "$$" = { 625 -7625 16250 125 AFC_FIXED_INCR  }
					CjmExternalChannelPresets "jmClkExtChannelPresets" "$$" {
					}
					CjmDemuxPresets "jmClkDemuxPresets" "$$" {
						CafcLongCell "jmClkDemuxVector" "$$" = { 0  }
						CafcLongCell "jmClkDemuxXfactor" "$$" = { 2  }
					}
					CafcLongLongCell "jmClkMaxSyncSpeed" "$$" = { -1 -9223372036854775807 9223372036854775807 1 AFC_FIXED_INCR  }
				}
			}
			CjmStatusTypeManager "jmClkStatusTypeManager" "$$" {
				CafcByteCell "JmSBMStatusTypeSaveRestore" "$$" = { 3  0 255 }
			}
		}
		CcmSupportedLA "SupportedLA" "$$" {
			CafcStringCell "PackageName" "$$" = { "ISA"  }
			RDAInternalOpMarkSet "RDAOpMarkSet" "$$" {
			}
		}
		CcmFilters "Filters" "$$" {
			CcmFilter "Filter" "$Filter$" {
				CafcStringCell "UserName" "$$" = { "Filter"  }
				CafcStringCell "Description" "$$" = { ""  }
				CafcBooleanCell "FilterEnable" "$$" = { TRUE  }
				CcmFilterClauseDefs "FilterClauses" "$$" {
					CcmFilterClause "FilterClause" "$$" {
						CafcStringCell "UserName" "$$" = { ""  }
						CafcByteCell "FilterClauseType" "$$" = { 0  0 255 }
						CafcBooleanCell "FilterClauseDisable" "$$" = { FALSE  }
						CafcStringCell "GroupName" "$$" = { ""  }
						CafcLongCell "FilterForegroundColor" "$$" = { 0  }
						CafcLongCell "FilterBackgroundColor" "$$" = { 15658671  }
						CafcBooleanCell "FilterForegroundDisable" "$$" = { FALSE  }
						CafcBooleanCell "FilterBackgroundDisable" "$$" = { FALSE  }
						CcmFilterEventDefs "FilterEvents" "$$" {
							CcmFSEventProperties "FilterEvent" "$$" {
								CafcByteCell "SearchEventType" "$$" = { 4  0 255 }
								CafcBooleanCell "SearchEventBoolean" "$$" = { FALSE  }
							}
						}
					}
				}
			}
		}
	}
}